# .github/workflows/deploy.yml

name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Your bucket's region

      - name: Sync files to S3
        run: |
             name: Upload to S3
             run: aws s3 sync ./build s3://dockers3projectelevate
          # Use your unique S3 bucket name here
          aws s3 sync .s3-website-us-east-1.amazonaws.com --delete
